// Mock data — replace with Supabase queries later
export const PRODUCTS = [
  {
    id: 1,
    title_fr: 'Cours de mathématiques S2',
    title_ar: 'درس رياضيات الفصل الثاني',
    subject_fr: 'Mathématiques',
    subject_ar: 'رياضيات',
    level: 'lycee',
    type: 'course',
    price: 8,
    pages: 42,
    downloads: 67,
    preview_pages: 5,
    description_fr: 'Résumé complet du programme de maths terminale. Inclut formules, exercices corrigés et méthodes.',
    description_ar: 'ملخص شامل لمنهج الرياضيات للبكالوريا. يتضمن صيغ وتمارين محلولة وطرق.',
    cover_color: '#e8f0fe',
    cover_accent: '#4f8ef7',
  },
  {
    id: 2,
    title_fr: 'Annales du Bac — Physique',
    title_ar: 'امتحانات البكالوريا — فيزياء',
    subject_fr: 'Physique',
    subject_ar: 'فيزياء',
    level: 'lycee',
    type: 'exam',
    price: 10,
    pages: 58,
    downloads: 54,
    preview_pages: 4,
    description_fr: 'Compilation des sujets de physique du bac des 5 dernières années avec corrections détaillées.',
    description_ar: 'مجموعة مواضيع فيزياء البكالوريا للسنوات الخمس الماضية مع تصحيحات مفصلة.',
    cover_color: '#fef3c7',
    cover_accent: '#f59e0b',
  },
  {
    id: 3,
    title_fr: 'Projet informatique — Base de données',
    title_ar: 'مشروع إعلامية — قواعد البيانات',
    subject_fr: 'Informatique',
    subject_ar: 'إعلامية',
    level: 'uni',
    type: 'project',
    price: 15,
    pages: 34,
    downloads: 43,
    preview_pages: 3,
    description_fr: 'Projet complet de conception et implémentation d\'une base de données relationnelle avec rapport.',
    description_ar: 'مشروع كامل لتصميم وتطبيق قاعدة بيانات علائقية مع تقرير.',
    cover_color: '#f0fdf4',
    cover_accent: '#22c55e',
  },
  {
    id: 4,
    title_fr: 'Résumé de droit des obligations',
    title_ar: 'ملخص قانون الالتزامات',
    subject_fr: 'Droit',
    subject_ar: 'قانون',
    level: 'uni',
    type: 'course',
    price: 12,
    pages: 48,
    downloads: 33,
    preview_pages: 4,
    description_fr: 'Résumé clair et structuré du cours de droit des obligations en première année de droit.',
    description_ar: 'ملخص واضح ومنظم لمادة قانون الالتزامات في السنة الأولى حقوق.',
    cover_color: '#fce7f3',
    cover_accent: '#ec4899',
  },
  {
    id: 5,
    title_fr: 'Devoir de physique corrigé',
    title_ar: 'واجب فيزياء محلول',
    subject_fr: 'Physique',
    subject_ar: 'فيزياء',
    level: 'lycee',
    type: 'homework',
    price: 5,
    pages: 12,
    downloads: 21,
    preview_pages: 2,
    description_fr: 'Devoir maison corrigé sur la mécanique, avec toutes les étapes de résolution détaillées.',
    description_ar: 'واجب بيتي مصحح في الميكانيكا مع كل خطوات الحل بالتفصيل.',
    cover_color: '#ede9fe',
    cover_accent: '#7c3aed',
  },
  {
    id: 6,
    title_fr: 'Formation Excel avancé',
    title_ar: 'تكوين إكسل متقدم',
    subject_fr: 'Bureautique',
    subject_ar: 'مكتبيات',
    level: 'pro',
    type: 'course',
    price: 20,
    pages: 65,
    downloads: 18,
    preview_pages: 5,
    description_fr: 'Guide complet Excel avancé : tableaux croisés, macros VBA, formules complexes et dashboards.',
    description_ar: 'دليل شامل لإكسل المتقدم: الجداول المحورية، ماكرو VBA، الصيغ المعقدة واللوحات.',
    cover_color: '#ecfdf5',
    cover_accent: '#059669',
  },
];

export const LEVELS = ['lycee', 'uni', 'pro'];
export const TYPES = ['course', 'homework', 'project', 'exam'];
